
export let COURSES_FETCH = 'COURSES_FETCH'
export let COURSES_SUCCESS = 'COURSES_SUCCESS'

export let ADD_QUERY = 'ADD_QUERY'
export let REMOVE_QUERY = 'REMOVE_QUERY'
export let MODIFY_QUERY = 'MODIFY_QUERY'
export let ENABLE_QUERY = 'ENABLE_QUERY'
export let DISABLE_QUERY = 'DISABLE_QUERY'
export let TOGGLE_QUERY = 'TOGGLE_QUERY'

export let ADD_SECTIONS = 'ADD_SECTIONS'
export let REMOVE_SECTIONS = 'REMOVE_SECTIONS'
export let MODIFY_SECTIONS = 'MODIFY_SECTIONS'
export let ENABLE_SECTIONS = 'ENABLE_SECTIONS'
export let DISABLE_SECTIONS = 'DISABLE_SECTIONS'
export let TOGGLE_SECTIONS = 'TOGGLE_SECTIONS'
