
export let COURSES_FETCH = 'COURSES_FETCH'
export let COURSES_SUCCESS = 'COURSES_SUCCESS'

export let ADD_QUERY = 'ADD_QUERY'
export let REMOVE_QUERY = 'REMOVE_QUERY'
export let MODIFY_QUERY = 'MODIFY_QUERY'
export let ENABLE_QUERY = 'ENABLE_QUERY'
export let DISABLE_QUERY = 'DISABLE_QUERY'
export let TOGGLE_QUERY = 'TOGGLE_QUERY'
export let ENABLE_SECTION = 'ENABLE_SECTION'
export let DISABLE_SECTION = 'DISABLE_SECTION'
export let TOGGLE_SECTION = 'TOGGLE_SECTION'

export let UPDATE_RESULTS = 'UPDATE_RESULTS'
